title: The Mir Blog
email: team@mir.rocks
description: > # this means to ignore newlines until "baseurl:"
  The Mir Blog. Stay in touch with the lastest developments
  in scientific computing for D.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.mir.dlang.io" # the base hostname & protocol for your site
twitter_username: libmir
github_username:  libmir
github_repo: libmir/blog

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

katex:
    path_to_js: "./js/katex.min.js"

# jekyll doesn't like bundler
exclude: ["vendor"]

category_dir: categories
